app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"



# fos_user_security_login:
#     path:      /login
#     defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

# fos_user_security_logout:
#     path:      /login
#     defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }